export const colors = [
  {
    name: "red",
    hex: "#ed0a3f",
    aliases: ["rose", "smell-the-roses", "magic-potion"],
    groups: ["standard", "magic-scent", "color-n-smell", "silly-scents"],
  },
  {
    name: "maroon",
    hex: "#c32148",
    aliases: ["dark-red", "cherry", "dingy-dungeon"],
    groups: ["standard", "magic-scent", "silly-scents"],
  },
  {
    name: "scarlet",
    hex: "#fd0e35",
    aliases: ["torch-red"],
    groups: ["standard"],
  },
  {
    name: "brick-red",
    hex: "#c62d42",
    aliases: ["earthworm"],
    groups: ["standard", "color-n-smell"],
  },
  {
    name: "english-vermilion",
    hex: "#cc474b",
    aliases: ["english-vermillion"],
    groups: ["standard"],
  },
  {
    name: "madder-lake",
    hex: "#cc3336",
    groups: ["standard"],
  },
  {
    name: "permanent-geranium-lake",
    hex: "#e12c2c",
    groups: ["standard"],
  },
  {
    name: "maximum-red",
    hex: "#d92121",
    groups: ["standard"],
  },
  {
    name: "chestnut",
    hex: "#b94e48",
    aliases: ["indian-red", "giants-club"],
    groups: ["standard", "silly-scents"],
  },
  {
    name: "orange-red",
    hex: "#ff5349",
    groups: ["standard"],
  },
  {
    name: "sunset-orange",
    hex: "#fe4c40",
    groups: ["standard"],
  },
  {
    name: "bittersweet",
    hex: "#fe6f5e",
    groups: ["standard"],
  },
  {
    name: "dark-venetian-red",
    hex: "#b33b24",
    aliases: ["venetian-red-dark"],
    groups: ["standard"],
  },
  {
    name: "venetian-red",
    hex: "#cc553d",
    groups: ["standard"],
  },
  {
    name: "light-venetian-red",
    hex: "#e6735c",
    aliases: ["venetian-red-light"],
    groups: ["standard"],
  },
  {
    name: "vivid-tangerine",
    hex: "#ff9980",
    groups: ["standard"],
  },
  {
    name: "middle-red",
    hex: "#e58e73",
    groups: ["standard"],
  },
  {
    name: "burnt-orange",
    hex: "#ff7034",
    groups: ["standard"],
  },
  {
    name: "red-orange",
    hex: "#ff681f",
  	aliases: ["ogre-odor"],
    groups: ["standard", "silly-scents"],
  },
  {
    name: "orange",
    hex: "#ff8833",
    aliases: ["jelly-bean", "tulip", "grandmas-perfume", "smashed-pumpkin"],
    groups: ["standard", "magic-scent", "color-n-smell", "silly-scents"],
  },
  {
    name: "macaroni-and-cheese",
    hex: "#ffb97b",
    aliases: ["macaroni-n-cheese"],
    groups: ["standard"],
  },
  {
    name: "middle-yellow-red",
    hex: "#ecb176",
    aliases: ["medium-orange"],
    groups: ["standard"],
  },
  {
    name: "mango-tango",
    hex: "#e77200",
  	aliases: ["sunburnt-cyclops"],
    groups: ["standard", "silly-scents"],
  },
  {
    name: "yellow-orange",
    hex: "#ffae42",
    groups: ["standard"],
  },
  {
    name: "maximum-yellow-red",
    hex: "#f2ba49",
    groups: ["standard"],
  },
  {
    name: "banana-mania",
    hex: "#fbe7b2",
    groups: ["standard"],
  },
  {
    name: "maize",
    hex: "#f2c649",
    aliases: ["gold-ochre", "golden-ochre"],
    groups: ["standard"],
  },
  {
    name: "orange-yellow",
    hex: "#f8d568",
    groups: ["standard"],
},
  {
    name: "goldenrod",
    hex: "#fcd667",
    aliases: ["medium-chrome-yellow", "medium-yellow", "sharpening-pencils"],
    groups: ["standard", "color-n-smell"],
  },
  {
    name: "dandelion",
    hex: "#fed85d",
    aliases: ["banana", "wash-the-dog", "gargoyle-gas"],
    groups: ["standard", "magic-scent", "color-n-smell", "silly-scents"],
  },
  {
    name: "yellow",
    hex: "#fbe870",
    aliases: ["daffodil", "lemon", "sunny-day"],
    groups: ["standard", "magic-scent", "color-n-smell"],
  },
  {
    name: "green-yellow",
    hex: "#f1e788",
    groups: ["standard"],
  },
  {
    name: "middle-yellow",
    hex: "#ffeb00",
    groups: ["standard"],
  },
  {
    name: "olive-green",
    hex: "#b5b35c",
    groups: ["standard"],
  },
  {
    name: "spring-green",
    hex: "#ecebbd",
  	aliases: ["booger-buster"],
    groups: ["standard", "silly-scents"],
},
  {
    name: "maximum-yellow",
    hex: "#fafa37",
    groups: ["standard"],
  },
  {
    name: "canary",
    hex: "#ffff99",
    aliases: ["blonde-hair"],
    groups: ["standard", "colors-of-the-world"],
  },
  {
    name: "lemon-yellow",
    hex: "#ffff9f",
    aliases: ["light-chrome-yellow", "chrome-yellow-light", "light-yellow"],
    groups: ["standard"],
  },
  {
    name: "maximum-green-yellow",
    hex: "#d9e650",
    groups: ["standard"],
  },
  {
    name: "middle-green-yellow",
    hex: "#acbf60",
    groups: ["standard"],
  },
  {
    name: "inchworm",
    hex: "#afe313",
    groups: ["standard"],
  },
  {
    name: "light-chrome-green",
    hex: "#bee64b",
    aliases: ["chrome-green-light"],
    groups: ["standard"],
  },
  {
    name: "yellow-green",
    hex: "#c5e17a",
    aliases: ["lime", "alien-armpit"],
    groups: ["standard", "magic-scent", "silly-scents"],
  },
  {
    name: "maximum-green",
    hex: "#5e8c31",
    groups: ["standard"],
  },
  {
    name: "asparagus",
    hex: "#7ba05b",
    aliases: ["green-eyes"],
    groups: ["standard", "colors-of-the-world"],
  },
  {
    name: "granny-smith-apple",
    hex: "#9de093",
    groups: ["standard"],
  },
  {
    name: "fern",
    hex: "#63b76c",
    groups: ["standard"],
  },
  {
    name: "middle-green",
    hex: "#4d8c57",
    groups: ["standard"],
  },
  {
    name: "green",
    hex: "#01a638",
    groups: ["standard"],
  },
  {
    name: "medium-chrome-green",
    hex: "#6ca67c",
    aliases: ["chrome-green-medium", "medium-green"],
    groups: ["standard"],
  },
  {
    name: "forest-green",
    hex: "#5fa777",
    aliases: ["dark green"],
    groups: ["standard"],
  },
  {
    name: "sea-green",
    hex: "#93dfb8",
    aliases: ["light-green"],
    groups: ["standard"],
  },
  {
    name: "shamrock",
    hex: "#33cc99",
    groups: ["standard"],
  },
  {
    name: "mountain-meadow",
    hex: "#1ab385",
    groups: ["standard"],
  },
  {
    name: "jungle-green",
    hex: "#29ab87",
    aliases: ["eucalyptus", "koala-tree"],
    groups: ["standard", "magic-scent", "color-n-smell"],
  },
  {
    name: "caribbean-green",
    hex: "#00cc99",
    groups: ["standard"],
  },
  {
    name: "tropical-rain-forest",
    hex: "#00755e",
    groups: ["standard"],
  },
  {
    name: "middle-blue-green",
    hex: "#8dd9cc",
    groups: ["standard"],
  },
  {
    name: "pine-green",
    hex: "#01796f",
    aliases: ["dark-chrome-green", "chrome-green-dark", "dark-green", "pine", "pine-tree"],
    groups: ["standard", "magic-scent", "color-n-smell"],
  },
  {
    name: "maximum-blue-green",
    hex: "#30bfbf",
    groups: ["standard"],
  },
  {
    name: "robins-egg-blue",
    hex: "#00cccc",
  	aliases: ["sea-serpent"],
    groups: ["standard", "silly-scents"],
  },
  {
    name: "teal-blue",
    hex: "#008080",
    groups: ["standard"],
  },
  {
    name: "light-blue",
    hex: "#8fd8d8",
    groups: ["standard"],
  },
  {
    name: "aquamarine",
    hex: "#95e0e8",
    aliases: ["light-turquoise-blue"],
    groups: ["standard"],
  },
  {
    name: "turquoise-blue",
    hex: "#6cdae7",
    aliases: ["blue-eyes"],
    groups: ["standard", "colors-of-the-world"],
  },
  {
    name: "outer-space",
    hex: "#2d383a",
    groups: ["standard"],
  },
  {
    name: "sky-blue",
    hex: "#76d7ea",
    aliases: ["fresh-air", "winter-wizard"],
    groups: ["standard", "magic-scent", "color-n-smell", "silly-scents"],
  },
  {
    name: "middle-blue",
    hex: "#7ed4e6",
    groups: ["standard"],
  },
  {
    name: "blue-green",
    hex: "#0095b7",
    groups: ["standard"],
  },
  {
    name: "pacific-blue",
    hex: "#009dc4",
    groups: ["standard"],
  },
  {
    name: "cerulean",
    hex: "#02a4d3",
    groups: ["standard"],
  },
  {
    name: "maximum-blue",
    hex: "#47abcc",
    groups: ["standard"],
  },
  {
    name: "blue-i",
    hex: "#4997d0",
    aliases: ["azure-blue"],
    groups: ["standard"],
  },
  {
    name: "cerulean-blue",
    hex: "#339acc",
    groups: ["standard"],
  },
  {
    name: "cornflower",
    hex: "#93ccea",
    groups: ["standard"],
  },
  {
    name: "green-blue",
    hex: "#2887c8",
    groups: ["standard"],
  },
  {
    name: "midnight-blue",
    hex: "#003366",
    aliases: ["prussian-blue"],
    groups: ["standard"],
  },
  {
    name: "navy-blue",
    hex: "#0066cc",
    groups: ["standard"],
  },
  {
    name: "denim",
    hex: "#1560bd",
    groups: ["standard"],
  },
  {
    name: "blue-iii",
    hex: "#0066ff",
    aliases: ["new-car"],
    groups: ["standard", "magic-scent"],
  },
  {
    name: "cadet-blue",
    hex: "#a9b2c3",
    groups: ["standard"],
  },
  {
    name: "periwinkle",
    hex: "#c3cde6",
    aliases: ["soap"],
    groups: ["standard", "magic-scent"],
  },
  {
    name: "blue-ii",
    hex: "#4570e6", 
    aliases: ["medium-blue", "blueberry"],
    groups: ["standard", "magic-scent"],
  },
  {
    name: "bluetiful",
    hex: "#3c69e7",
    groups: ["standard"],
  },
  {
    name: "wild-blue-yonder",
    hex: "#7a89b8",
    groups: ["standard"],
  },
  {
    name: "indigo",
    hex: "#4f69c6",
    groups: ["standard"],
  },
  {
    name: "manatee",
    hex: "#8d90a1",
    groups: ["standard"],
  },
  {
    name: "cobalt-blue",
    hex: "#8c90c8",
    groups: ["standard"],
  },
  {
    name: "celestial-blue",
    hex: "#7070cc",
    groups: ["standard"],
  },
  {
    name: "blue-bell",
    hex: "#9999cc",
    groups: ["standard"],
  },
  {
    name: "maximum-blue-purple",
    hex: "#acace6",
    groups: ["standard"],
  },
  {
    name: "violet-blue",
    hex: "#766ec8",
    groups: ["standard"],
  },
  {
    name: "blue-violet",
    hex: "#6456b7",
    aliases: ["violet", "pixie-powder"],
    groups: ["standard", "silly-scents"],
  },
  {
    name: "ultramarine-blue",
    hex: "#3f26bf",
    groups: ["standard"],
  },
  {
    name: "middle-blue-purple",
    hex: "#8b72be",
    groups: ["standard"],
  },
  {
    name: "purple-heart",
    hex: "#652dc1",
    groups: ["standard"],
  },
  {
    name: "royal-purple",
    hex: "#6b3fa0",
    groups: ["standard"],
  },
  {
    name: "violet-ii",
    hex: "#8359a3",
    aliases: ["violet-purple", "grape"],
    groups: ["standard", "magic-scent"],
  },
  {
    name: "medium-violet",
    hex: "#8f47b3",
    groups: ["standard"],
  },
  {
    name: "wisteria",
    hex: "#c9a0dc",
    aliases: ["lilac", "flower-shop"],
    groups: ["standard", "magic-scent", "color-n-smell"],
  },
  {
    name: "lavender-i",
    hex: "#bf8fcc",
    groups: ["standard"],
  },
  {
    name: "vivid-violet",
    hex: "#803790",
    aliases: ["frostbite"],
    groups: ["standard", "extreme-twistables"],
  },
  {
    name: "maximum-purple",
    hex: "#733380",
    groups: ["standard"],
  },
  {
    name: "purple-mountains-majesty",
    hex: "#d6aedd",
    aliases: ["purple-mountain-majesty"],
    groups: ["standard"],
  },
  {
    name: "fuchsia",
    hex: "#c154c1",
    groups: ["standard"],
  },
  {
    name: "pink-flamingo",
    hex: "#fc74fd",
    groups: ["standard"],
  },
  {
    name: "violet-i",
    hex: "#732e6c",
    aliases: ["purple"],
    groups: ["standard"],
  },
  {
    name: "brilliant-rose",
    hex: "#e667ce",
    groups: ["standard"],
  },
  {
    name: "orchid",
    hex: "#e29cd2",
    aliases: ["medium-red-violet"],
    groups: ["standard"],
  },
  {
    name: "plum",
    hex: "#8e3179",
    groups: ["standard"],
  },
  {
    name: "medium-rose",
    hex: "#d96cbe",
    groups: ["standard"],
  },
  {
    name: "thistle",
    hex: "#d8bfd8",
    aliases: ["light-magenta"],
    groups: ["standard"],
  },
  {
    name: "mulberry",
    hex: "#c8509b",
    groups: ["standard"],
  },
  {
    name: "red-violet",
    hex: "#bb3385",
    groups: ["standard"],
  },
  {
    name: "middle-purple",
    hex: "#d982b5",
    groups: ["standard"],
  },
  {
    name: "maximum-red-purple",
    hex: "#a63a79",
    groups: ["standard"],
  },
  {
    name: "jazzberry-jam",
    hex: "#a50b5e",
    groups: ["standard"],
  },
  {
    name: "eggplant",
    hex: "#614051",
    groups: ["standard"],
  },
  {
    name: "magenta",
    hex: "#f653a6",
    aliases: ["permanent-magenta"],
    groups: ["standard"],
  },
  {
    name: "cerise",
    hex: "#da3287",
    groups: ["standard"],
  },
  {
    name: "wild-strawberry",
    hex: "#ff3399",
    aliases: ["strawberry"],
    groups: ["standard", "magic-scent", "gel-fx"],
  },
  {
    name: "lavender-ii",
    hex: "#fbaed2",
    groups: ["standard"],
  },
  {
    name: "cotton-candy",
    hex: "#ffb7d5",
    groups: ["standard"],
  },
  {
    name: "carnation-pink",
    hex: "#ffa6c9",
    aliases: ["rose-pink", "pink", "shampoo"],
    groups: ["standard", "magic-scent"],
  },
  {
    name: "violet-red",
    hex: "#f7468a",
  	aliases: ["sasquatch-socks"],
    groups: ["standard", "silly-scents"],
  },
  {
    name: "razzmatazz",
    hex: "#e30b5c",
    groups: ["standard"],
  },
  {
    name: "piggy-pink",
    hex: "#fdd7e4",
    aliases: ["pig-pink"],
    groups: ["standard"],
  },
  {
    name: "carmine",
    hex: "#e62e6b",
    aliases: ["carmine-red"],
    groups: ["standard"],
  },
  {
    name: "blush",
    hex: "#db5079",
    aliases: ["cranberry"],
    groups: ["standard"],
  },
  {
    name: "tickle-me-pink",
    hex: "#fc80a5",
    aliases: ["bubble-gum", "bubble-bath", "princess-perfume"],
    groups: ["standard", "magic-scent", "color-n-smell", "silly-scents"],
  },
  {
    name: "mauvelous",
    hex: "#f091a9",
    groups: ["standard"],
  },
  {
    name: "salmon",
    hex: "#ff91a4",
    groups: ["standard"],
  },
  {
    name: "middle-red-purple",
    hex: "#a55353",
    groups: ["standard"],
  },
  {
    name: "mahogany",
    hex: "#ca3435",
    aliases: ["cedar-chest", "red-hair"],
    groups: ["standard", "multicultural", "magic-scent", "colors-of-the-world"],
  },
  {
    name: "melon",
    hex: "#febaad",
    groups: ["standard"],
  },
  {
    name: "pink-sherbert",
    hex: "#f7a38e",
    aliases: ["brink-pink"],
    groups: ["standard"],
  },
  {
    name: "burnt-sienna",
    hex: "#e97451",
    aliases: ["baseball-mitt"],
    groups: ["standard", "multicultural", "color-n-smell"],
  },
  {
    name: "brown",
    hex: "#af593e",
    aliases: ["chocolate", "pet-shop", "brown-eyes"],
    groups: ["standard", "magic-scent", "color-n-smell", "colors-of-the-world"],
  },
  {
    name: "sepia",
    hex: "#9e5b40",
    aliases: ["dirt", "brown-hair"],
    groups: ["standard", "multicultural", "magic-scent", "colors-of-the-world"],
  },
  {
    name: "fuzzy-wuzzy",
    hex: "#87421f",
    aliases: ["fuzzy-wuzzy-brown"],
    groups: ["standard"],
  },
  {
    name: "beaver",
    hex: "#926f5b",
    groups: ["standard"],
  },
  {
    name: "tumbleweed",
    hex: "#dea681",
    groups: ["standard"],
  },
  {
    name: "raw-sienna",
    hex: "#d27d46",
    aliases: ["hazel-eyes"],
    groups: ["standard", "colors-of-the-world"],
  },
  {
    name: "van-dyke-brown",
    hex: "#664228",
    groups: ["standard"],
  },
  {
    name: "tan",
    hex: "#fa9d5a",
  	aliases: ["big-foot-feet"],
    groups: ["standard", "multicultural", "silly-scents"],
  },
  {
    name: "desert-sand",
    hex: "#edc9af",
    groups: ["standard"],
  },
  {
    name: "peach",
    hex: "#ffcba4",
    aliases: ["flesh-tint", "flesh", "pink-beige", "saw-dust"],
    groups: ["standard", "multicultural", "magic-scent", "color-n-smell"],
  },
  {
    name: "burnt-umber",
    hex: "#805533",
    groups: ["standard"],
  },
  {
    name: "apricot",
    hex: "#fdd5b1",
    aliases: ["lumber"],
    groups: ["standard", "multicultural", "magic-scent"],
  },
  {
    name: "almond",
    hex: "#eed9c4",
    groups: ["standard"],
  },
  {
    name: "raw-umber",
    hex: "#665233",
    groups: ["standard"],
  },
  {
    name: "shadow",
    hex: "#837050",
    groups: ["standard"],
  },
  {
    name: "raw-sienna-i",
    hex: "#e6bc5c",
    groups: ["standard"],
  },
  {
    name: "gold-i",
    hex: "#92926e",
    groups: ["standard"],
  },
  {
    name: "gold-ii",
    hex: "#e6be8a",
    groups: ["standard"],
  },
  {
    name: "silver",
    hex: "#c9c0bb",
    groups: ["standard"],
  },
  {
    name: "copper",
    hex: "#da8a67",
    groups: ["standard"],
  },
  {
    name: "antique-brass",
    hex: "#c88a65",
    groups: ["standard"],
  },
  {
    name: "black",
    hex: "#000000",
    aliases: ["leather-jacket", "licorice", "new-sneakers", "black-hair"],
    groups: ["standard", "multicultural", "magic-scent", "color-n-smell", "colors-of-the-world"],
  },
  {
    name: "charcoal-gray",
    hex: "#736a62",
    aliases: ["charcoal-grey"],
    groups: ["standard"],
  },
  {
    name: "gray",
    hex: "#8b8680",
    aliases: ["middle-grey", "grey", "neutral-grey", "smoke", "mummys-tomb"],
    groups: ["standard", "magic-scent", "silly-scents"],
  },
  {
    name: "blue-gray",
    hex: "#c8c8cd",
    aliases: ["blue-grey"],
    groups: ["standard"],
  },
  {
    name: "timberwolf",
    hex: "#d9d6cf",
    groups: ["standard"],
  },
  {
    name: "white",
    hex: "#ffffff",
    aliases: ["baby-powder", "coconut", "babys-powder"],
    groups: ["standard", "multicultural", "magic-scent", "color-n-smell", "gel-fx"],
  },
  {
    name: "crayellow",
    hex: "#f1d651",
    groups: ["standard"],
  },
  {
    name: "cool-mint",
    hex: "#ddebec",
    groups: ["standard"],
  },
  {
    name: "oatmeal",
    hex: "#d9dad2",
    groups: ["standard"],
  },
  {
    name: "powder-blue",
    hex: "#c0d5f0",
    groups: ["standard"],
  },
  {
    name: "radical-red",
    hex: "#ff355e",
    groups: ["fluorescent"],
  },
  {
    name: "wild-watermelon",
    hex: "#fd5b78",
    aliases: ["ultra-red", "heat-wave"],
    groups: ["fluorescent", "extreme-twistables"],
  },
  {
    name: "outrageous-orange",
    hex: "#ff6037",
    aliases: ["ultra-orange"],
    groups: ["fluorescent"],
  },
  {
    name: "atomic-tangerine",
    hex: "#ff9966",
    aliases: ["ultra-yellow", "sizzling-sunset"],
    groups: ["fluorescent", "extreme-twistables"],
  },
  {
    name: "neon-carrot",
    hex: "#ff9933",
    groups: ["fluorescent"],
  },
  {
    name: "sunglow",
    hex: "#ffcc33",
    groups: ["fluorescent"],
  },
  {
    name: "laser-lemon",
    hex: "#ffff66",
    aliases: ["chartreuse", "unmellow-yellow", "lemon-glacier"],
    groups: ["fluorescent", "extreme-twistables"],
  },
  {
    name: "electric-lime",
    hex: "#ccff00",
    groups: ["fluorescent"],
  },
  {
    name: "screamin-green",
    hex: "#66ff66",
    aliases: ["ultra-green", "spring-frost"],
    groups: ["fluorescent", "extreme-twistables"],
  },
  {
    name: "magic-mint",
    hex: "#aaf0d1",
    groups: ["fluorescent"],
  },
  {
    name: "blizzard-blue",
    hex: "#50bfe6",
    aliases: ["ultra-blue", "absolute-zero"],
    groups: ["fluorescent", "extreme-twistables"],
  },
  {
    name: "shocking-pink",
    hex: "#ff6eff",
    aliases: ["ultra-pink"],
    groups: ["fluorescent"],
  },
  {
    name: "razzle-dazzle-rose",
    hex: "#ee34d2",
    aliases: ["fiery-rose"],
    groups: ["fluorescent", "extreme-twistables"],
  },
  {
    name: "hot-magenta",
    hex: "#ff00cc",
    aliases: ["winter-sky"],
    groups: ["fluorescent", "extreme-twistables"],
  },
  {
    name: "purple-pizzazz",
    hex: "#ff00bb",
    groups: ["fluorescent"],
  },
  {
    name: "aztec-gold",
    hex: "#c39953",
    groups: ["silver-swirls"],
  },
  {
    name: "burnished-brown",
    hex: "#a17a74",
    groups: ["silver-swirls"],
  },
  {
    name: "cerulean-frost",
    hex: "#6d9bc3",
    groups: ["silver-swirls"],
  },
  {
    name: "cinnamon-satin",
    hex: "#cd607e",
    groups: ["silver-swirls"],
  },
  {
    name: "copper-penny",
    hex: "#ad6f69",
    groups: ["silver-swirls"],
  },
  {
    name: "cosmic-cobalt",
    hex: "#2e2d88",
    groups: ["silver-swirls"],
  },
  {
    name: "glossy-grape",
    hex: "#ab92b3",
    groups: ["silver-swirls"],
  },
  {
    name: "granite-gray",
    hex: "#676767",
    aliases: ["granite-grey"],
    groups: ["silver-swirls"],
  },
  {
    name: "green-sheen",
    hex: "#6eaea1",
    groups: ["silver-swirls"],
  },
  {
    name: "lilac-luster",
    hex: "#ae98aa",
    groups: ["silver-swirls"],
  },
  {
    name: "misty-moss",
    hex: "#bbb477",
    groups: ["silver-swirls"],
  },
  {
    name: "mystic-maroon",
    hex: "#ad4379",
    groups: ["silver-swirls"],
  },
  {
    name: "pearly-purple",
    hex: "#b768a2",
    groups: ["silver-swirls"],
  },
  {
    name: "pewter-blue",
    hex: "#8ba8b7",
    groups: ["silver-swirls"],
  },
  {
    name: "polished-pine",
    hex: "#5da493",
    groups: ["silver-swirls"],
  },
  {
    name: "quick-silver",
    hex: "#a6a6a6",
    groups: ["silver-swirls"],
  },
  {
    name: "rose-dust",
    hex: "#9e5e6f",
    groups: ["silver-swirls"],
  },
  {
    name: "rusty-red",
    hex: "#da2c43",
    groups: ["silver-swirls"],
  },
  {
    name: "shadow-blue",
    hex: "#778ba5",
    groups: ["silver-swirls"],
  },
  {
    name: "shiny-shamrock",
    hex: "#5fa778",
    groups: ["silver-swirls"],
  },
  {
    name: "steel-teal",
    hex: "#5f8a8b",
    groups: ["silver-swirls"],
  },
  {
    name: "sugar-plum",
    hex: "#914e75",
    groups: ["silver-swirls"],
  },
  {
    name: "twilight-lavender",
    hex: "#8a496b",
    groups: ["silver-swirls"],
  },
  {
    name: "wintergreen-dream",
    hex: "#56887d",
    groups: ["silver-swirls"],
  },
  {
    name: "amethyst",
    hex: "#64609a",
    groups: ["gem-tones"],
  },
  {
    name: "citrine",
    hex: "#933709",
    groups: ["gem-tones"],
  },
  {
    name: "emerald",
    hex: "#14a989",
    groups: ["gem-tones"],
  },
  {
    name: "jade",
    hex: "#469a84",
    groups: ["gem-tones"],
  },
  {
    name: "jasper",
    hex: "#d05340",
    groups: ["gem-tones"],
  },
  {
    name: "lapis-lazuli",
    hex: "#436cb9",
    groups: ["gem-tones"],
  },
  {
    name: "malachite",
    hex: "#469496",
    groups: ["gem-tones"],
  },
  {
    name: "moonstone",
    hex: "#3aa8c1",
    groups: ["gem-tones"],
  },
  {
    name: "onyx",
    hex: "#353839",
    groups: ["gem-tones"],
  },
  {
    name: "peridot",
    hex: "#abad48",
    groups: ["gem-tones"],
  },
  {
    name: "pink-pearl",
    hex: "#b07080",
    groups: ["gem-tones"],
  },
  {
    name: "rose-quartz",
    hex: "#bd559c",
    groups: ["gem-tones"],
  },
  {
    name: "ruby",
    hex: "#aa4069",
    groups: ["gem-tones"],
  },
  {
    name: "sapphire",
    hex: "#2d5da1",
    groups: ["gem-tones"],
  },
  {
    name: "smokey-topaz",
    hex: "#832a0d",
    groups: ["gem-tones"],
  },
  {
    name: "tigers-eye",
    hex: "#b56917",
    groups: ["gem-tones"],
  },
  {
    name: "carnation-pink-star-brite",
    hex: "#f898c8",
    groups: ["star-brite"],
  },
  {
    name: "ruby-star-brite",
    hex: "#e91e63",
    groups: ["star-brite"],
  },
  {
    name: "harley-davidson-orange",
    hex: "#d62518",
    groups: ["star-brite"],
  },
  {
    name: "free-speech-red",
    hex: "#ad0000",
    groups: ["star-brite"],
  },
  {
    name: "tangerine",
    hex: "#fa7a00",
    groups: ["star-brite"],
  },
  {
    name: "las-palmas",
    hex: "#cddc39",
    groups: ["star-brite"],
  },
  {
    name: "caribbean-green-star-brite",
    hex: "#00d8a0",
    groups: ["star-brite"],
  },
  {
    name: "mountain-meadow-star-brite",
    hex: "#1ba77b",
    groups: ["star-brite"],
  },
  {
    name: "dark-cerulean",
    hex: "#004c71",
    groups: ["star-brite"],
  },
  {
    name: "summer-sky",
    hex: "#1aade0",
    groups: ["star-brite"],
  },
  {
    name: "navy-blue-star-brite",
    hex: "#0069bd",
    groups: ["star-brite"],
  },
  {
    name: "dark-slate-blue",
    hex: "#333399",
    groups: ["star-brite"],
  },
  {
    name: "gigas",
    hex: "#56418c",
    groups: ["star-brite"],
  },
  {
    name: "black-bean",
    hex: "#212321",
    groups: ["star-brite"],
  },
  {
    name: "scarlet-star-brite",
    hex: "#e63300",
    groups: ["star-brite"],
  },
  {
    name: "mango-tango-star-brite",
    hex: "#de6900",
    groups: ["star-brite"],
  },
  {
    name: "aqua-pearl",
    hex: "#5fbed7",
    groups: ["pearl-brite"],
  },
  {
    name: "black-coral-pearl",
    hex: "#54626f",
    groups: ["pearl-brite"],
  },
  {
    name: "caribbean-green-pearl",
    hex: "#6ada8e",
    groups: ["pearl-brite"],
  },
  {
    name: "cultured-pearl",
    hex: "#f5f5f5",
    groups: ["pearl-brite"],
  },
  {
    name: "key-lime-pearl",
    hex: "#e8f48c",
    groups: ["pearl-brite"],
  },
  {
    name: "mandarin-pearl",
    hex: "#f37a48",
    groups: ["pearl-brite"],
  },
  {
    name: "midnight-pearl",
    hex: "#702670",
    groups: ["pearl-brite"],
  },
  {
    name: "mystic-pearl",
    hex: "#d65282",
    groups: ["pearl-brite"],
  },
  {
    name: "ocean-blue-pearl",
    hex: "#4f42b5",
    groups: ["pearl-brite"],
  },
  {
    name: "ocean-green-pearl",
    hex: "#48bf91",
    groups: ["pearl-brite"],
  },
  {
    name: "orchid-pearl",
    hex: "#7b4259",
    groups: ["pearl-brite"],
  },
  {
    name: "rose-pearl",
    hex: "#f03865",
    groups: ["pearl-brite"],
  },
  {
    name: "salmon-pearl",
    hex: "#f1444a",
    groups: ["pearl-brite"],
  },
  {
    name: "sunny-pearl",
    hex: "#f2f27a",
    groups: ["pearl-brite"],
  },
  {
    name: "sunset-pearl",
    hex: "#f1cc79",
    groups: ["pearl-brite"],
  },
  {
    name: "turquoise-pearl",
    hex: "#3bbcd0",
    groups: ["pearl-brite"],
  },
  {
    name: "alloy-orange",
    hex: "#c46210",
    groups: ["metallic-fx"],
  },
  {
    name: "bdazzled-blue",
    hex: "#2e5894",
    groups: ["metallic-fx"],
  },
  {
    name: "big-dip-o-ruby",
    hex: "#9c2542",
    groups: ["metallic-fx"],
  },
  {
    name: "bittersweet-shimmer",
    hex: "#bf4f51",
    groups: ["metallic-fx"],
  },
  {
    name: "blast-off-bronze",
    hex: "#a57164",
    groups: ["metallic-fx"],
  },
  {
    name: "cyber-grape",
    hex: "#58427c",
    groups: ["metallic-fx"],
  },
  {
    name: "deep-space-sparkle",
    hex: "#4a646c",
    groups: ["metallic-fx"],
  },
  {
    name: "gold-fusion",
    hex: "#85754e",
    groups: ["metallic-fx"],
  },
  {
    name: "illuminating-emerald",
    hex: "#319177",
    groups: ["metallic-fx"],
  },
  {
    name: "metallic-seaweed",
    hex: "#0a7e8c",
    groups: ["metallic-fx"],
  },
  {
    name: "robot-canary",
    hex: "#9c7c38",
    aliases: ["metallic-sunburst"],
    groups: ["metallic-fx"],
  },
  {
    name: "razzmic-berry",
    hex: "#8d4e85",
    groups: ["metallic-fx"],
  },
  {
    name: "sheen-green",
    hex: "#8fd400",
    groups: ["metallic-fx"],
  },
  {
    name: "shimmering-blush",
    hex: "#d98695",
    groups: ["metallic-fx"],
  },
  {
    name: "sonic-silver",
    hex: "#757575",
    groups: ["metallic-fx"],
  },
  {
    name: "steel-blue",
    hex: "#0081ab",
    groups: ["metallic-fx"],
  },
  {
    name: "cheese-grater",
    hex: "#c89f56",
    groups: ["metallic-fx"],
  },
  {
    name: "iron-indigo",
    hex: "#184fa1",
    groups: ["metallic-fx"],
  },
  {
    name: "magnetic-magenta",
    hex: "#bf3981",
    groups: ["metallic-fx"],
  },
  {
    name: "cobalt-cool",
    hex: "#028aae",
    groups: ["metallic-fx"],
  },
  {
    name: "acid-wash-jeans",
    hex: "#5cb2c5",
    groups: ["metallic-fx"],
  },
  {
    name: "petrified-forest",
    hex: "#005b39",
    groups: ["metallic-fx"],
  },
  {
    name: "rose-gold",
    hex: "#c88ca4",
    groups: ["metallic-fx"],
  },
  {
    name: "gold-medal",
    hex: "#c5bc42",
    groups: ["metallic-fx"],
  },
  {
    name: "brilliant-rose-gel-fx",
    hex: "#ff6699",
    groups: ["gel-fx"],
  },
  {
    name: "froly",
    hex: "#f26d7d",
    groups: ["gel-fx"],
  },
  {
    name: "flamenco",
    hex: "#f58345",
    groups: ["gel-fx"],
  },
  {
    name: "macaroni-and-cheese-gel-fx",
    hex: "#ffbf7f",
    groups: ["gel-fx"],
  },
  {
    name: "dolly",
    hex: "#f5ff7d",
    groups: ["gel-fx"],
  },
  {
    name: "mint-green",
    hex: "#99ff99",
    groups: ["gel-fx"],
  },
  {
    name: "bright-turquoise",
    hex: "#12e3db",
    groups: ["gel-fx"],
  },
  {
    name: "iris-blue",
    hex: "#00b6bd",
    groups: ["gel-fx"],
  },
  {
    name: "dodger-blue",
    hex: "#0081ff",
    groups: ["gel-fx"],
  },
  {
    name: "wild-blue-yonder-gel-fx",
    hex: "#7092be",
    groups: ["gel-fx"],
  },
  {
    name: "free-speech-blue",
    hex: "#3f48cc",
    groups: ["gel-fx"],
  },
  {
    name: "studio",
    hex: "#7853a8",
    groups: ["gel-fx"],
  },
  {
    name: "violet-blue-gel-fx",
    hex: "#a349a4",
    groups: ["gel-fx"],
  },
  {
    name: "mauve-taupe",
    hex: "#8f5873",
    groups: ["gel-fx"],
  },
  {
    name: "antique-gray",
    hex: "#9f9f9f",
    aliases: ["antique-grey"],
    groups: ["pearl"],
  },
  {
    name: "apple-orchard",
    hex: "#bf3f3f",
    groups: ["pearl"],
  },
  {
    name: "berry-parfait",
    hex: "#a43482",
    groups: ["pearl"],
  },
  {
    name: "black-pearl",
    hex: "#3a3a3a",
    groups: ["pearl"],
  },
  {
    name: "bubble-gum-pearl",
    hex: "#df9aca",
    groups: ["pearl"],
  },
  {
    name: "butternut-squash",
    hex: "#e74f00",
    groups: ["pearl"],
  },
  {
    name: "caribbean-sea",
    hex: "#67cd95",
    groups: ["pearl"],
  },
  {
    name: "cloudy-sky",
    hex: "#548cd0",
    groups: ["pearl"],
  },
  {
    name: "hot-cocoa",
    hex: "#8f482f",
    groups: ["pearl"],
  },
  {
    name: "iridescent-indigo",
    hex: "#3c32cd",
    groups: ["pearl"],
  },
  {
    name: "lavender-silk",
    hex: "#6b4d82",
    groups: ["pearl"],
  },
  {
    name: "leafy-canopy",
    hex: "#94ddcb",
    groups: ["pearl"],
  },
  {
    name: "liquid-gold",
    hex: "#ffd966",
    groups: ["pearl"],
  },
  {
    name: "mango-puree",
    hex: "#ff6137",
    groups: ["pearl"],
  },
  {
    name: "moonlit-pond",
    hex: "#4f2cd0",
    groups: ["pearl"],
  },
  {
    name: "ocean-foam",
    hex: "#62c9d3",
    groups: ["pearl"],
  },
  {
    name: "orange-peel",
    hex: "#ff8021",
    groups: ["pearl"],
  },
  {
    name: "pesto",
    hex: "#5f7b4a",
    groups: ["pearl"],
  },
  {
    name: "pink-luster",
    hex: "#ffb2e7",
    groups: ["pearl"],
  },
  {
    name: "red-satin",
    hex: "#9f3434",
    groups: ["pearl"],
  },
  {
    name: "sea-glass",
    hex: "#c4ea7f",
    groups: ["pearl"],
  },
  {
    name: "shooting-star",
    hex: "#ffff65",
    groups: ["pearl"],
  },
  {
    name: "snow-drift",
    hex: "#f3f3f3",
    groups: ["pearl"],
  },
  {
    name: "sunset-shimmer",
    hex: "#f79015",
    groups: ["pearl"],
  },
  {
    name: "deep-almond",
    hex: "#986a5a",
    groups: ["colors-of-the-world"],
  },
  {
    name: "deep-golden",
    hex: "#8d5b28",
    groups: ["colors-of-the-world"],
  },
  {
    name: "deep-rose",
    hex: "#b86f69",
    groups: ["colors-of-the-world"],
  },
  {
    name: "deepest-almond",
    hex: "#513529",
    groups: ["colors-of-the-world"],
  },
  {
    name: "extra-deep-almond",
    hex: "#6e5046",
    groups: ["colors-of-the-world"],
  },
  {
    name: "extra-deep-golden",
    hex: "#5f452e",
    groups: ["colors-of-the-world"],
  },
  {
    name: "extra-deep-rose",
    hex: "#6c4d4b",
    groups: ["colors-of-the-world"],
  },
  {
    name: "extra-light-almond",
    hex: "#eee6cf",
    groups: ["colors-of-the-world"],
  },
  {
    name: "light-almond",
    hex: "#e6b9b3",
    groups: ["colors-of-the-world"],
  },
  {
    name: "light-golden",
    hex: "#eddbc7",
    groups: ["colors-of-the-world"],
  },
  {
    name: "light-medium-almond",
    hex: "#e0b5a4",
    groups: ["colors-of-the-world"],
  },
  {
    name: "light-medium-golden",
    hex: "#f0c9a2",
    groups: ["colors-of-the-world"],
  },
  {
    name: "light-medium-rose",
    hex: "#f4afb2",
    groups: ["colors-of-the-world"],
  },
  {
    name: "light-rose",
    hex: "#fac7c3",
    groups: ["colors-of-the-world"],
  },
  {
    name: "medium-almond",
    hex: "#d19c7d",
    groups: ["colors-of-the-world"],
  },
  {
    name: "medium-deep-almond",
    hex: "#ac8065",
    groups: ["colors-of-the-world"],
  },
  {
    name: "medium-deep-golden",
    hex: "#a16b4f",
    groups: ["colors-of-the-world"],
  },
  {
    name: "medium-deep-rose",
    hex: "#ee8e99",
    groups: ["colors-of-the-world"],
  },
  {
    name: "medium-golden",
    hex: "#dea26c",
    groups: ["colors-of-the-world"],
  },
  {
    name: "very-deep-almond",
    hex: "#88605e",
    groups: ["colors-of-the-world"],
  },
  {
    name: "very-deep-rose",
    hex: "#8f6c68",
    groups: ["colors-of-the-world"],
  },
  {
    name: "very-light-almond",
    hex: "#e6d2d3",
    groups: ["colors-of-the-world"],
  },
  {
    name: "very-light-golden",
    hex: "#f0dfcf",
    groups: ["colors-of-the-world"],
  },
  {
    name: "very-light-rose",
    hex: "#f7e1e3",
    groups: ["colors-of-the-world"],
  },
  {
    name: "sizzling-red",
    hex: "#ff3855",
    groups: ["heads-n-tails"],
  },
  {
    name: "red-salsa",
    hex: "#fd3a4a",
    groups: ["heads-n-tails"],
  },
  {
    name: "tart-orange",
    hex: "#fb4d46",
    groups: ["heads-n-tails"],
  },
  {
    name: "orange-soda",
    hex: "#fa5b3d",
    groups: ["heads-n-tails"],
  },
  {
    name: "bright-yellow",
    hex: "#ffaa1d",
    groups: ["heads-n-tails"],
  },
  {
    name: "yellow-sunshine",
    hex: "#fff700",
    groups: ["heads-n-tails"],
  },
  {
    name: "slimy-green",
    hex: "#299617",
    groups: ["heads-n-tails"],
  },
  {
    name: "green-lizard",
    hex: "#a7f432",
    groups: ["heads-n-tails"],
  },
  {
    name: "denim-blue",
    hex: "#2243b6",
    groups: ["heads-n-tails"],
  },
  {
    name: "blue-jeans",
    hex: "#5dadec",
    groups: ["heads-n-tails"],
  },
  {
    name: "plump-purple",
    hex: "#5946b2",
    groups: ["heads-n-tails"],
  },
  {
    name: "purple-plum",
    hex: "#9c51b6",
    groups: ["heads-n-tails"],
  },
  {
    name: "sweet-brown",
    hex: "#a83731",
    groups: ["heads-n-tails"],
  },
  {
    name: "brown-sugar",
    hex: "#af6e4d",
    groups: ["heads-n-tails"],
  },
  {
    name: "eerie-black",
    hex: "#1b1b1b",
    groups: ["heads-n-tails"],
  },
  {
    name: "black-shadows",
    hex: "#bfafb2",
    groups: ["heads-n-tails"],
  },
  {
 	  name: "blue-ribbon",
    hex: "#0b10a2",
    groups: ["the-100-billionth-crayon"],
  },
]
