export const colors = [
  {
    name: "absolute-zero",
    hex: "#0048ba",
    groups: ["extreme-twistables"],
  },
  {
    name: "alien-armpit",
    hex: "#84de02",
    groups: ["silly-scents"],
  },
  {
    name: "alloy-orange",
    hex: "#c46210",
    groups: ["metallic-fx"],
  },
  {
    name: "almond",
    hex: "#eed9c4",
    groups: ["standard"],
  },
  {
    name: "amethyst",
    hex: "#64609a",
    groups: ["gem-tones"],
  },
  {
    name: "antique-brass",
    hex: "#c88a65",
    groups: ["standard"],
  },
  {
    name: "apricot",
    hex: "#fdd5b1",
    groups: ["standard", "multicultural", "twistables"],
  },
  {
    name: "aqua-pearl",
    hex: "#5fbed7",
    groups: ["pearl-brite"],
  },
  {
    name: "aquamarine",
    hex: "#95e0e8",
    groups: ["standard"],
    aliases: ["light-turquoise-blue"],
  },
  {
    name: "asparagus",
    hex: "#7ba05b",
    groups: ["standard"],
  },
  {
    name: "atomic-tangerine",
    hex: "#ff9966",
    groups: ["fluorescent"],
    aliases: ["ultra-yellow"],
  },
  {
    name: "aztec-gold",
    hex: "#c39953",
    groups: ["silver-swirls"],
  },
  {
    name: "azure-blue",
    hex: "#4997d0",
    groups: ["standard"],
    aliases: ["blue-i"],
  },
  {
    name: "baby-powder",
    hex: "#fefefa",
    groups: ["magic-scent"],
  },
  {
    name: "banana",
    hex: "#ffd12a",
    groups: ["magic-scent"],
  },
  {
    name: "banana-mania",
    hex: "#fbe7b2",
    groups: ["standard"],
  },
  {
    name: "bdazzled-blue",
    hex: "#2e5894",
    groups: ["metallic-fx"],
  },
  {
    name: "beaver",
    hex: "#926f5b",
    groups: ["standard"],
  },
  {
    name: "big-dip-o-ruby",
    hex: "#9c2542",
    groups: ["metallic-fx"],
  },
  {
    name: "big-foot-feet",
    hex: "#e88e5a",
    groups: ["silly-scents"],
  },
  {
    name: "bittersweet",
    hex: "#fe6f5e",
    groups: ["standard"],
  },
  {
    name: "bittersweet-shimmer",
    hex: "#bf4f51",
    groups: ["metallic-fx"],
  },
  {
    name: "black",
    hex: "#000000",
    groups: ["standard", "multicultural", "color-n-smell:new-sneakers", "twistables"],
  },
  {
    name: "black-coral-pearl",
    hex: "#54626f",
    groups: ["pearl-brite"],
  },
  {
    name: "black-shadows",
    hex: "#bfafb2",
    groups: ["heads-n-tails"],
  },
  {
    name: "blast-off-bronze",
    hex: "#a57164",
    groups: ["metallic-fx"],
  },
  {
    name: "blizzard-blue",
    hex: "#50bfe6",
    groups: ["fluorescent"],
    aliases: ["ultra-blue"],
  },
  {
    name: "blue",
    hex: "#0066ff",
    groups: ["standard", "twistables"],
  },
  {
    name: "blue-bell",
    hex: "#9999cc",
    groups: ["standard"],
  },
  {
    name: "blue-gray",
    hex: "#c8c8cd",
    groups: ["standard"],
    aliases: ["blue-grey"],
  },
  {
    name: "blue-green",
    hex: "#0095b7",
    groups: ["standard", "twistables"],
  },
  {
    name: "blue-jeans",
    hex: "#5dadec",
    groups: ["heads-n-tails"],
  },
  {
    name: "blue-violet",
    hex: "#6456b7",
    groups: ["standard", "twistables"],
  },
  {
    name: "blueberry",
    hex: "#4f86f7",
    groups: ["magic-scent"],
  },
  {
    name: "blush",
    hex: "#db5079",
    groups: ["standard"],
    aliases: ["cranberry"],
  },
  {
    name: "booger-buster",
    hex: "#dde26a",
    groups: ["silly-scents"],
  },
  {
    name: "brick-red",
    hex: "#c62d42",
    groups: ["standard", "color-n-smell:earthworm"],
  },
  {
    name: "bright-yellow",
    hex: "#ffaa1d",
    groups: ["heads-n-tails"],
  },
  {
    name: "brilliant-rose",
    hex: "#e667ce",
    groups: ["standard"],
  },
  {
    name: "brown",
    hex: "#af593e",
    groups: ["standard", "color-n-smell:pet-shop", "twistables"],
  },
  {
    name: "brown-sugar",
    hex: "#af6e4d",
    groups: ["heads-n-tails"],
  },
  {
    name: "bubble-gum",
    hex: "#ffd3f8",
    groups: ["magic-scent"],
  },
  {
    name: "burnished-brown",
    hex: "#a17a74",
    groups: ["silver-swirls"],
  },
  {
    name: "burnt-orange",
    hex: "#ff7f49",
    groups: ["standard"],
  },
  {
    name: "burnt-sienna",
    hex: "#e97451",
    groups: ["standard", "multicultural", "color-n-smell:baseball-mitt"],
  },
  {
    name: "burnt-umber",
    hex: "#805533",
    groups: ["standard"],
  },
  {
    name: "cadet-blue",
    hex: "#a9b2c3",
    groups: ["standard"],
  },
  {
    name: "canary",
    hex: "#ffff99",
    groups: ["standard"],
  },
  {
    name: "caribbean-green",
    hex: "#00cc99",
    groups: ["standard"],
  },
  {
    name: "caribbean-green-pearl",
    hex: "#6ada8e",
    groups: ["pearl-brite"],
  },
  {
    name: "carmine",
    hex: "#e62e6b",
    groups: ["standard"],
    aliases: ["carmine-red"],
  },
  {
    name: "carnation-pink",
    hex: "#ffa6c9",
    groups: ["standard", "twistables"],
    aliases: ["rose-pink", "pink"],
  },
  {
    name: "cedar-chest",
    hex: "#c95a49",
    groups: ["magic-scent"],
  },
  {
    name: "celestial-blue",
    hex: "#7070cc",
    groups: ["standard"],
  },
  {
    name: "cerise",
    hex: "#da3287",
    groups: ["standard"],
  },
  {
    name: "cerulean",
    hex: "#02a4d3",
    groups: ["standard", "twistables"],
  },
  {
    name: "cerulean-blue",
    hex: "#339acc",
    groups: ["standard"],
  },
  {
    name: "cerulean-frost",
    hex: "#6d9bc3",
    groups: ["silver-swirls"],
  },
  {
    name: "charcoal-gray",
    hex: "#736a62",
    groups: ["standard"],
    aliases: ["charcoal-grey"],
  },
  {
    name: "cherry",
    hex: "#da2647",
    groups: ["magic-scent"],
  },
  {
    name: "chestnut",
    hex: "#b94e48",
    groups: ["standard"],
    aliases: ["indian-red"],
  },
  {
    name: "chocolate",
    hex: "#bd8260",
    groups: ["magic-scent"],
  },
  {
    name: "cinnamon-satin",
    hex: "#cd607e",
    groups: ["silver-swirls"],
  },
  {
    name: "citrine",
    hex: "#933709",
    groups: ["gem-tones"],
  },
  {
    name: "cobalt-blue",
    hex: "#8c90c8",
    groups: ["standard"],
  },
  {
    name: "coconut",
    hex: "#fefefe",
    groups: ["magic-scent"],
  },
  {
    name: "copper",
    hex: "#da8a67",
    groups: ["standard"],
  },
  {
    name: "copper-penny",
    hex: "#ad6f69",
    groups: ["silver-swirls"],
  },
  {
    name: "cornflower",
    hex: "#93ccea",
    groups: ["standard"],
  },
  {
    name: "cosmic-cobalt",
    hex: "#2e2d88",
    groups: ["silver-swirls"],
  },
  {
    name: "cotton-candy",
    hex: "#ffb7d5",
    groups: ["standard"],
  },
  {
    name: "cultured-pearl",
    hex: "#f5f5f5",
    groups: ["pearl-brite"],
  },
  {
    name: "cyber-grape",
    hex: "#58427c",
    groups: ["metallic-fx"],
  },
  {
    name: "daffodil",
    hex: "#ffff31",
    groups: ["magic-scent"],
  },
  {
    name: "dandelion",
    hex: "#fed85d",
    groups: ["standard", "color-n-smell:wash-the-dog", "twistables"],
  },
  {
    name: "dark-venetian-red",
    hex: "#b33b24",
    groups: ["standard"],
    aliases: ["venetian-red-dark"],
  },
  {
    name: "deep-space-sparkle",
    hex: "#4a646c",
    groups: ["metallic-fx"],
  },
  {
    name: "denim",
    hex: "#1560bd",
    groups: ["standard"],
  },
  {
    name: "denim-blue",
    hex: "#2243b6",
    groups: ["heads-n-tails"],
  },
  {
    name: "desert-sand",
    hex: "#edc9af",
    groups: ["standard"],
  },
  {
    name: "dingy-dungeon",
    hex: "#c53151",
    groups: ["silly-scents"],
  },
  {
    name: "dirt",
    hex: "#9b7653",
    groups: ["magic-scent"],
  },
  {
    name: "eerie-black",
    hex: "#1b1b1b",
    groups: ["heads-n-tails"],
  },
  {
    name: "eggplant",
    hex: "#614051",
    groups: ["standard"],
  },
  {
    name: "electric-lime",
    hex: "#ccff00",
    groups: ["fluorescent"],
  },
  {
    name: "emerald",
    hex: "#14a989",
    groups: ["gem-tones"],
  },
  {
    name: "english-vermilion",
    hex: "#cc474b",
    groups: ["standard"],
    aliases: ["english-vermillion"],
  },
  {
    name: "eucalyptus",
    hex: "#44d7a8",
    groups: ["magic-scent"],
  },
  {
    name: "fern",
    hex: "#63b76c",
    groups: ["standard"],
  },
  {
    name: "fiery-rose",
    hex: "#ff5470",
    groups: ["extreme-twistables"],
  },
  {
    name: "forest-green",
    hex: "#5fa777",
    groups: ["standard"],
    aliases: ["dark-green"],
  },
  {
    name: "fresh-air",
    hex: "#a6e7ff",
    groups: ["magic-scent"],
  },
  {
    name: "frostbite",
    hex: "#e936a7",
    groups: ["extreme-twistables"],
  },
  {
    name: "fuchsia",
    hex: "#c154c1",
    groups: ["standard"],
  },
  {
    name: "fuzzy-wuzzy",
    hex: "#87421f",
    groups: ["standard"],
    aliases: ["fuzzy-wuzzy-brown"],
  },
  {
    name: "gargoyle-gas",
    hex: "#ffdf46",
    groups: ["silly-scents"],
  },
  {
    name: "giants-club",
    hex: "#b05c52",
    groups: ["silly-scents"],
  },
  {
    name: "glossy-grape",
    hex: "#ab92b3",
    groups: ["silver-swirls"],
  },
  {
    name: "gold",
    hex: "#e6be8a",
    groups: ["standard"],
  },
  {
    name: "gold-fusion",
    hex: "#85754e",
    groups: ["metallic-fx"],
  },
  {
    name: "gold-i",
    hex: "#92926e",
    groups: ["standard"],
  },
  {
    name: "goldenrod",
    hex: "#fcd667",
    groups: ["standard", "color-n-smell:sharpening-pencils"],
    aliases: ["medium-chrome-yellow", "medium-yellow"],
  },
  {
    name: "granite-gray",
    hex: "#676767",
    groups: ["silver-swirls"],
    aliases: ["granite-grey"],
  },
  {
    name: "granny-smith-apple",
    hex: "#9de093",
    groups: ["standard"],
  },
  {
    name: "grape",
    hex: "#6f2da8",
    groups: ["magic-scent"],
  },
  {
    name: "gray",
    hex: "#8b8680",
    groups: ["standard", "twistables"],
    aliases: ["grey", "middle-gray", "middle-grey", "neutral-gray", "neutral-grey"],
  },
  {
    name: "green",
    hex: "#3aa655",
    groups: ["standard", "twistables"],
  },
  {
    name: "green-blue",
    hex: "#2887c8",
    groups: ["standard"],
  },
  {
    name: "green-lizard",
    hex: "#a7f432",
    groups: ["heads-n-tails"],
  },
  {
    name: "green-sheen",
    hex: "#6eaea1",
    groups: ["silver-swirls"],
  },
  {
    name: "green-yellow",
    hex: "#f1e788",
    groups: ["standard", "twistables"],
  },
  {
    name: "heat-wave",
    hex: "#ff7a00",
    groups: ["extreme-twistables"],
  },
  {
    name: "hot-magenta",
    hex: "#ff00cc",
    groups: ["fluorescent"],
  },
  {
    name: "illuminating-emerald",
    hex: "#319177",
    groups: ["metallic-fx"],
  },
  {
    name: "inchworm",
    hex: "#afe313",
    groups: ["standard"],
  },
  {
    name: "indigo",
    hex: "#4f69c6",
    groups: ["standard", "twistables"],
  },
  {
    name: "jade",
    hex: "#469a84",
    groups: ["gem-tones"],
  },
  {
    name: "jasper",
    hex: "#d05340",
    groups: ["gem-tones"],
  },
  {
    name: "jazzberry-jam",
    hex: "#a50b5e",
    groups: ["standard"],
  },
  {
    name: "jelly-bean",
    hex: "#da614e",
    groups: ["magic-scent"],
  },
  {
    name: "jungle-green",
    hex: "#29ab87",
    groups: ["standard", "color-n-smell:koala-tree"],
  },
  {
    name: "key-lime-pearl",
    hex: "#e8f48c",
    groups: ["pearl-brite"],
  },
  {
    name: "lapis-lazuli",
    hex: "#436cb9",
    groups: ["gem-tones"],
  },
  {
    name: "laser-lemon",
    hex: "#ffff66",
    groups: ["fluorescent"],
    aliases: ["chartreuse"],
  },
  {
    name: "lavender",
    hex: "#fbaed2",
    groups: ["standard"],
  },
  {
    name: "lavender-i",
    hex: "#bf8fcc",
    groups: ["standard"],
  },
  {
    name: "leather-jacket",
    hex: "#253529",
    groups: ["magic-scent"],
  },
  {
    name: "lemon",
    hex: "#ffff38",
    groups: ["magic-scent"],
  },
  {
    name: "lemon-glacier",
    hex: "#fdff00",
    groups: ["extreme-twistables"],
  },
  {
    name: "lemon-yellow",
    hex: "#ffff9f",
    groups: ["standard"],
    aliases: ["light-chrome-yellow", "chrome-yellow-light", "light-yellow"],
  },
  {
    name: "licorice",
    hex: "#1a1110",
    groups: ["magic-scent"],
  },
  {
    name: "light-blue",
    hex: "#8fd8d8",
    groups: ["standard"],
  },
  {
    name: "light-chrome-green",
    hex: "#bee64b",
    groups: ["standard"],
    aliases: ["chrome-green-light"],
  },
  {
    name: "light-venetian-red",
    hex: "#e6735c",
    groups: ["standard"],
    aliases: ["venetian-red-light"],
  },
  {
    name: "lilac",
    hex: "#db91ef",
    groups: ["magic-scent"],
  },
  {
    name: "lilac-luster",
    hex: "#ae98aa",
    groups: ["silver-swirls"],
  },
  {
    name: "lime",
    hex: "#b2f302",
    groups: ["magic-scent"],
  },
  {
    name: "lumber",
    hex: "#ffe4cd",
    groups: ["magic-scent"],
  },
  {
    name: "macaroni-and-cheese",
    hex: "#ffb97b",
    groups: ["standard"],
    aliases: ["macaroni-n-cheese"],
  },
  {
    name: "madder-lake",
    hex: "#cc3336",
    groups: ["standard"],
  },
  {
    name: "magenta",
    hex: "#f653a6",
    groups: ["standard"],
    aliases: ["permanent-magenta"],
  },
  {
    name: "magic-mint",
    hex: "#aaf0d1",
    groups: ["fluorescent"],
  },
  {
    name: "magic-potion",
    hex: "#ff4466",
    groups: ["silly-scents"],
  },
  {
    name: "mahogany",
    hex: "#ca3435",
    groups: ["standard", "multicultural"],
  },
  {
    name: "maize",
    hex: "#f2c649",
    groups: ["standard"],
    aliases: ["gold-ochre", "golden-ochre"],
  },
  {
    name: "malachite",
    hex: "#469496",
    groups: ["gem-tones"],
  },
  {
    name: "manatee",
    hex: "#8d90a1",
    groups: ["standard"],
  },
  {
    name: "mandarin-pearl",
    hex: "#f37a48",
    groups: ["pearl-brite"],
  },
  {
    name: "mango-tango",
    hex: "#e77200",
    groups: ["standard"],
  },
  {
    name: "maroon",
    hex: "#c32148",
    groups: ["standard"],
    aliases: ["dark-red"],
  },
  {
    name: "mauvelous",
    hex: "#f091a9",
    groups: ["standard"],
  },
  {
    name: "maximum-blue",
    hex: "#47abcc",
    groups: ["standard"],
  },
  {
    name: "maximum-blue-green",
    hex: "#30bfbf",
    groups: ["standard"],
  },
  {
    name: "maximum-blue-purple",
    hex: "#acace6",
    groups: ["standard"],
  },
  {
    name: "maximum-green",
    hex: "#5e8c31",
    groups: ["standard"],
  },
  {
    name: "maximum-green-yellow",
    hex: "#d9e650",
    groups: ["standard"],
  },
  {
    name: "maximum-purple",
    hex: "#733380",
    groups: ["standard"],
  },
  {
    name: "maximum-red",
    hex: "#d92121",
    groups: ["standard"],
  },
  {
    name: "maximum-red-purple",
    hex: "#a63a79",
    groups: ["standard"],
  },
  {
    name: "maximum-yellow",
    hex: "#fafa37",
    groups: ["standard"],
  },
  {
    name: "maximum-yellow-red",
    hex: "#f2ba49",
    groups: ["standard"],
  },
  {
    name: "medium-blue",
    hex: "#4570e6",
    groups: ["standard"],
    aliases: ["blue-ii"],
  },
  {
    name: "medium-chrome-green",
    hex: "#6ca67c",
    groups: ["standard"],
    aliases: ["chrome-green-medium", "medium-green"],
  },
  {
    name: "medium-rose",
    hex: "#d96cbe",
    groups: ["standard"],
  },
  {
    name: "medium-violet",
    hex: "#8f47b3",
    groups: ["standard"],
  },
  {
    name: "melon",
    hex: "#febaad",
    groups: ["standard"],
  },
  {
    name: "metallic-seaweed",
    hex: "#0a7e8c",
    groups: ["metallic-fx"],
  },
  {
    name: "metallic-sunburst",
    hex: "#9c7c38",
    groups: ["metallic-fx"],
  },
  {
    name: "middle-blue",
    hex: "#7ed4e6",
    groups: ["standard"],
  },
  {
    name: "middle-blue-green",
    hex: "#8dd9cc",
    groups: ["standard"],
  },
  {
    name: "middle-blue-purple",
    hex: "#8b72be",
    groups: ["standard"],
  },
  {
    name: "middle-green",
    hex: "#4d8c57",
    groups: ["standard"],
  },
  {
    name: "middle-green-yellow",
    hex: "#acbf60",
    groups: ["standard"],
  },
  {
    name: "middle-purple",
    hex: "#d982b5",
    groups: ["standard"],
  },
  {
    name: "middle-red",
    hex: "#e58e73",
    groups: ["standard"],
  },
  {
    name: "middle-red-purple",
    hex: "#a55353",
    groups: ["standard"],
  },
  {
    name: "middle-yellow",
    hex: "#ffeb00",
    groups: ["standard"],
  },
  {
    name: "middle-yellow-red",
    hex: "#ecb176",
    groups: ["standard"],
    aliases: ["medium-orange"],
  },
  {
    name: "midnight-blue",
    hex: "#00468c",
    groups: ["standard"],
    aliases: ["prussian-blue"],
  },
  {
    name: "midnight-pearl",
    hex: "#702670",
    groups: ["pearl-brite"],
  },
  {
    name: "misty-moss",
    hex: "#bbb477",
    groups: ["silver-swirls"],
  },
  {
    name: "moonstone",
    hex: "#3aa8c1",
    groups: ["gem-tones"],
  },
  {
    name: "mountain-meadow",
    hex: "#1ab385",
    groups: ["standard"],
  },
  {
    name: "mulberry",
    hex: "#c8509b",
    groups: ["standard"],
  },
  {
    name: "mummys-tomb",
    hex: "#828e84",
    groups: ["silly-scents"],
  },
  {
    name: "mystic-maroon",
    hex: "#ad4379",
    groups: ["silver-swirls"],
  },
  {
    name: "mystic-pearl",
    hex: "#d65282",
    groups: ["pearl-brite"],
  },
  {
    name: "navy-blue",
    hex: "#0066cc",
    groups: ["standard"],
  },
  {
    name: "neon-carrot",
    hex: "#ff9933",
    groups: ["fluorescent"],
  },
  {
    name: "new-car",
    hex: "#214fc6",
    groups: ["magic-scent"],
  },
  {
    name: "ocean-blue-pearl",
    hex: "#4f42b5",
    groups: ["pearl-brite"],
  },
  {
    name: "ocean-green-pearl",
    hex: "#48bf91",
    groups: ["pearl-brite"],
  },
  {
    name: "ogre-odor",
    hex: "#fd5240",
    groups: ["silly-scents"],
  },
  {
    name: "olive-green",
    hex: "#b5b35c",
    groups: ["standard"],
  },
  {
    name: "onyx",
    hex: "#353839",
    groups: ["gem-tones"],
  },
  {
    name: "orange",
    hex: "#ff8833",
    groups: ["standard", "magic-scent", "color-n-smell:grandmas-perfume", "twistables"],
  },
  {
    name: "orange-red",
    hex: "#ff5349",
    groups: ["standard"],
  },
  {
    name: "orange-soda",
    hex: "#fa5b3d",
    groups: ["heads-n-tails"],
  },
  {
    name: "orange-yellow",
    hex: "#f8d568",
    groups: ["standard"],
  },
  {
    name: "orchid",
    hex: "#e29cd2",
    groups: ["standard"],
    aliases: ["medium-red-violet"],
  },
  {
    name: "orchid-pearl",
    hex: "#7b4259",
    groups: ["pearl-brite"],
  },
  {
    name: "outer-space",
    hex: "#2d383a",
    groups: ["standard"],
  },
  {
    name: "outrageous-orange",
    hex: "#ff6037",
    groups: ["fluorescent"],
    aliases: ["ultra-orange"],
  },
  {
    name: "pacific-blue",
    hex: "#009dc4",
    groups: ["standard"],
  },
  {
    name: "peach",
    hex: "#ffcba4",
    groups: ["standard", "multicultural", "magic-scent", "color-n-smell:saw-dust"],
    aliases: ["flesh-tint", "flesh", "pink-beige"],
  },
  {
    name: "pearly-purple",
    hex: "#b768a2",
    groups: ["silver-swirls"],
  },
  {
    name: "peridot",
    hex: "#abad48",
    groups: ["gem-tones"],
  },
  {
    name: "periwinkle",
    hex: "#c3cde6",
    groups: ["standard"],
  },
  {
    name: "permanent-geranium-lake",
    hex: "#e12c2c",
    groups: ["standard"],
  },
  {
    name: "pewter-blue",
    hex: "#8ba8b7",
    groups: ["silver-swirls"],
  },
  {
    name: "pig-pink",
    hex: "#fdd7e4",
    groups: ["standard"],
    aliases: ["piggy-pink"],
  },
  {
    name: "pine",
    hex: "#45a27d",
    groups: ["magic-scent"],
  },
  {
    name: "pine-green",
    hex: "#01786f",
    groups: ["standard", "color-n-smell:pine-tree"],
    aliases: ["dark-chrome-green", "chrome-green-dark"],
  },
  {
    name: "pink-flamingo",
    hex: "#fc74fd",
    groups: ["standard"],
  },
  {
    name: "pink-pearl",
    hex: "#b07080",
    groups: ["gem-tones"],
  },
  {
    name: "pink-sherbert",
    hex: "#f7a38e",
    groups: ["standard"],
    aliases: ["brink-pink"],
  },
  {
    name: "pixie-powder",
    hex: "#391285",
    groups: ["silly-scents"],
  },
  {
    name: "plum",
    hex: "#8e3179",
    groups: ["standard"],
  },
  {
    name: "plump-purple",
    hex: "#5946b2",
    groups: ["heads-n-tails"],
  },
  {
    name: "polished-pine",
    hex: "#5da493",
    groups: ["silver-swirls"],
  },
  {
    name: "princess-perfume",
    hex: "#ff85cf",
    groups: ["silly-scents"],
  },
  {
    name: "purple",
    hex: "#732e6c",
    groups: ["standard"],
    aliases: ["violet-i"],
  },
  {
    name: "purple-heart",
    hex: "#652dc1",
    groups: ["standard"],
  },
  {
    name: "purple-mountains-majesty",
    hex: "#d6aedd",
    groups: ["standard"],
    aliases: ["purple-mountain-majesty"],
  },
  {
    name: "purple-pizzazz",
    hex: "#ff00cc",
    groups: ["fluorescent"],
  },
  {
    name: "purple-plum",
    hex: "#9c51b6",
    groups: ["heads-n-tails"],
  },
  {
    name: "quick-silver",
    hex: "#a6a6a6",
    groups: ["silver-swirls"],
  },
  {
    name: "radical-red",
    hex: "#ff355e",
    groups: ["fluorescent"],
  },
  {
    name: "raw-sienna",
    hex: "#d27d46",
    groups: ["standard"],
  },
  {
    name: "raw-sienna-i",
    hex: "#e6bc5c",
    groups: ["standard"],
  },
  {
    name: "raw-umber",
    hex: "#665233",
    groups: ["standard"],
  },
  {
    name: "razzle-dazzle-rose",
    hex: "#ee34d2",
    groups: ["fluorescent"],
  },
  {
    name: "razzmatazz",
    hex: "#e30b5c",
    groups: ["standard"],
  },
  {
    name: "razzmic-berry",
    hex: "#8d4e85",
    groups: ["metallic-fx"],
  },
  {
    name: "red",
    hex: "#ed0a3f",
    groups: ["standard", "color-n-smell:smell-the-roses", "twistables"],
  },
  {
    name: "red-orange",
    hex: "#ff681f",
    groups: ["standard", "twistables"],
  },
  {
    name: "red-salsa",
    hex: "#fd3a4a",
    groups: ["heads-n-tails"],
  },
  {
    name: "red-violet",
    hex: "#bb3385",
    groups: ["standard", "twistables"],
  },
  {
    name: "robins-egg-blue",
    hex: "#00cccc",
    groups: ["standard"],
  },
  {
    name: "rose",
    hex: "#ff5050",
    groups: ["magic-scent"],
  },
  {
    name: "rose-dust",
    hex: "#9e5e6f",
    groups: ["silver-swirls"],
  },
  {
    name: "rose-pearl",
    hex: "#f03865",
    groups: ["pearl-brite"],
  },
  {
    name: "rose-quartz",
    hex: "#bd559c",
    groups: ["gem-tones"],
  },
  {
    name: "royal-purple",
    hex: "#6b3fa0",
    groups: ["standard"],
  },
  {
    name: "ruby",
    hex: "#aa4069",
    groups: ["gem-tones"],
  },
  {
    name: "rusty-red",
    hex: "#da2c43",
    groups: ["silver-swirls"],
  },
  {
    name: "salmon",
    hex: "#ff91a4",
    groups: ["standard"],
  },
  {
    name: "salmon-pearl",
    hex: "#f1444a",
    groups: ["pearl-brite"],
  },
  {
    name: "sapphire",
    hex: "#2d5da1",
    groups: ["gem-tones"],
  },
  {
    name: "sasquatch-socks",
    hex: "#ff4681",
    groups: ["silly-scents"],
  },
  {
    name: "scarlet",
    hex: "#fd0e35",
    groups: ["standard", "twistables"],
    aliases: ["torch-red"],
  },
  {
    name: "screamin-green",
    hex: "#66ff66",
    groups: ["fluorescent"],
    aliases: ["ultra-green"],
  },
  {
    name: "sea-green",
    hex: "#93dfb8",
    groups: ["standard"],
    aliases: ["light-green"],
  },
  {
    name: "sea-serpent",
    hex: "#4bc7cf",
    groups: ["silly-scents"],
  },
  {
    name: "sepia",
    hex: "#9e5b40",
    groups: ["standard", "multicultural"],
  },
  {
    name: "shadow",
    hex: "#837050",
    groups: ["standard"],
  },
  {
    name: "shadow-blue",
    hex: "#778ba5",
    groups: ["silver-swirls"],
  },
  {
    name: "shampoo",
    hex: "#ffcff1",
    groups: ["magic-scent"],
  },
  {
    name: "shamrock",
    hex: "#33cc99",
    groups: ["standard"],
  },
  {
    name: "sheen-green",
    hex: "#8fd400",
    groups: ["metallic-fx"],
  },
  {
    name: "shimmering-blush",
    hex: "#d98695",
    groups: ["metallic-fx"],
  },
  {
    name: "shiny-shamrock",
    hex: "#5fa778",
    groups: ["silver-swirls"],
  },
  {
    name: "shocking-pink",
    hex: "#ff6eff",
    groups: ["fluorescent"],
    aliases: ["ultra-pink"],
  },
  {
    name: "silver",
    hex: "#c9c0bb",
    groups: ["standard"],
  },
  {
    name: "sizzling-red",
    hex: "#ff3855",
    groups: ["heads-n-tails"],
  },
  {
    name: "sizzling-sunset",
    hex: "#ffdb00",
    groups: ["extreme-twistables"],
  },
  {
    name: "sky-blue",
    hex: "#76d7ea",
    groups: ["standard", "color-n-smell:fresh-air"],
  },
  {
    name: "slimy-green",
    hex: "#299617",
    groups: ["heads-n-tails"],
  },
  {
    name: "smashed-pumpkin",
    hex: "#ff6d3a",
    groups: ["silly-scents"],
  },
  {
    name: "smoke",
    hex: "#738276",
    groups: ["magic-scent"],
  },
  {
    name: "smokey-topaz",
    hex: "#832a0d",
    groups: ["gem-tones"],
  },
  {
    name: "soap",
    hex: "#cec8ef",
    groups: ["magic-scent"],
  },
  {
    name: "sonic-silver",
    hex: "#757575",
    groups: ["metallic-fx"],
  },
  {
    name: "spring-frost",
    hex: "#87ff2a",
    groups: ["extreme-twistables"],
  },
  {
    name: "spring-green",
    hex: "#ecebbd",
    groups: ["standard"],
  },
  {
    name: "steel-blue",
    hex: "#0081ab",
    groups: ["metallic-fx"],
  },
  {
    name: "steel-teal",
    hex: "#5f8a8b",
    groups: ["silver-swirls"],
  },
  {
    name: "strawberry",
    hex: "#fc5a8d",
    groups: ["magic-scent"],
  },
  {
    name: "sugar-plum",
    hex: "#914e75",
    groups: ["silver-swirls"],
  },
  {
    name: "sunburnt-cyclops",
    hex: "#ff404c",
    groups: ["silly-scents"],
  },
  {
    name: "sunglow",
    hex: "#ffcc33",
    groups: ["fluorescent"],
  },
  {
    name: "sunny-pearl",
    hex: "#f2f27a",
    groups: ["pearl-brite"],
  },
  {
    name: "sunset-orange",
    hex: "#fe4c40",
    groups: ["standard"],
  },
  {
    name: "sunset-pearl",
    hex: "#f1cc79",
    groups: ["pearl-brite"],
  },
  {
    name: "sweet-brown",
    hex: "#a83731",
    groups: ["heads-n-tails"],
  },
  {
    name: "tan",
    hex: "#d99a6c",
    groups: ["standard", "multicultural"],
  },
  {
    name: "tart-orange",
    hex: "#fb4d46",
    groups: ["heads-n-tails"],
  },
  {
    name: "teal-blue",
    hex: "#008080",
    groups: ["standard"],
  },
  {
    name: "thistle",
    hex: "#ebb0d7",
    groups: ["standard"],
    aliases: ["light-magenta"],
  },
  {
    name: "tickle-me-pink",
    hex: "#fc80a5",
    groups: ["standard", "color-n-smell:bubble-bath"],
  },
  {
    name: "tigers-eye",
    hex: "#b56917",
    groups: ["gem-tones"],
  },
  {
    name: "timberwolf",
    hex: "#d9d6cf",
    groups: ["standard"],
  },
  {
    name: "tropical-rain-forest",
    hex: "#00755e",
    groups: ["standard"],
  },
  {
    name: "tulip",
    hex: "#ff878d",
    groups: ["magic-scent"],
  },
  {
    name: "tumbleweed",
    hex: "#dea681",
    groups: ["standard"],
  },
  {
    name: "turquoise-blue",
    hex: "#6cdae7",
    groups: ["standard"],
  },
  {
    name: "turquoise-pearl",
    hex: "#3bbcd0",
    groups: ["pearl-brite"],
  },
  {
    name: "twilight-lavender",
    hex: "#8a496b",
    groups: ["silver-swirls"],
  },
  {
    name: "ultramarine-blue",
    hex: "#3f26bf",
    groups: ["standard"],
  },
  {
    name: "unmellow-yellow",
    hex: "#ffff66",
    groups: ["fluorescent"],
  },
  {
    name: "van-dyke-brown",
    hex: "#664228",
    groups: ["standard"],
  },
  {
    name: "venetian-red",
    hex: "#cc553d",
    groups: ["standard"],
  },
  {
    name: "violet",
    hex: "#8359a3",
    groups: ["standard", "twistables"],
  },
  {
    name: "violet-blue",
    hex: "#766ec8",
    groups: ["standard"],
  },
  {
    name: "violet-red",
    hex: "#f7468a",
    groups: ["standard", "twistables"],
  },
  {
    name: "vivid-tangerine",
    hex: "#ff9980",
    groups: ["standard"],
  },
  {
    name: "vivid-violet",
    hex: "#803790",
    groups: ["standard"],
  },
  {
    name: "white",
    hex: "#ffffff",
    groups: ["standard", "multicultural", "color-n-smell:babys-powder", "twistables"],
  },
  {
    name: "wild-blue-yonder",
    hex: "#7a89b8",
    groups: ["standard"],
  },
  {
    name: "wild-strawberry",
    hex: "#ff3399",
    groups: ["standard"],
  },
  {
    name: "wild-watermelon",
    hex: "#fd5b78",
    groups: ["fluorescent"],
    aliases: ["ultra-red"],
  },
  {
    name: "winter-sky",
    hex: "#ff007c",
    groups: ["extreme-twistables"],
  },
  {
    name: "winter-wizard",
    hex: "#a0e6ff",
    groups: ["silly-scents"],
  },
  {
    name: "wintergreen-dream",
    hex: "#56887d",
    groups: ["silver-swirls"],
  },
  {
    name: "wisteria",
    hex: "#c9a0dc",
    groups: ["standard", "color-n-smell:flower-shop"],
  },
  {
    name: "yellow",
    hex: "#fbe870",
    groups: ["standard", "color-n-smell:sunny-day", "twistables"],
  },
  {
    name: "yellow-green",
    hex: "#c5e17a",
    groups: ["standard", "twistables"],
  },
  {
    name: "yellow-orange",
    hex: "#ffae42",
    groups: ["standard", "twistables"],
  },
  {
    name: "yellow-sunshine",
    hex: "#fff700",
    groups: ["heads-n-tails"],
  },
]
